name: pansy_lint
description: Lints for Pansy Dev apps, packages, and plugins.
version: 1.0.0
repository: hhttps://github.com/pansydev/pansy_lint
issue_tracker: https://github.com/pansydev/pansy_lint/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
